const PDFDocument = require("pdfkit");

function generateScreeningPDF(record, res) {
  const doc = new PDFDocument({
    size: "A4",
    margin: 50,
  });

  // PDF response headers
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename="SwasthyaScan-Summary-${record._id}.pdf"`
  );

  // Pipe PDF directly to response
  doc.pipe(res);

  // =========================================
  // HEADER
  // =========================================

  doc
    .fontSize(24)
    .font("Helvetica-Bold")
    .text("SwasthyaScan", { align: "center" });

  doc
    .fontSize(12)
    .font("Helvetica")
    .text("Preliminary Health Risk Screening Summary", {
      align: "center",
    });

  doc.moveDown(1);

  // Divider
  doc
    .moveTo(50, doc.y)
    .lineTo(545, doc.y)
    .stroke();

  doc.moveDown(1);

  // =========================================
  // SCREENING DETAILS
  // =========================================

  doc
    .fontSize(16)
    .font("Helvetica-Bold")
    .text("Screening Details");

  doc.moveDown(0.5);

  doc.fontSize(11).font("Helvetica");

  doc.text(`Name: ${record.name || "Not provided"}`);
  doc.text(`Age: ${record.age}`);
  doc.text(`Gender: ${record.gender}`);
  doc.text(`Screened For: ${record.screenedFor}`);
  doc.text(
    `Date: ${new Date(record.createdAt).toLocaleString("en-IN")}`
  );

  doc.moveDown(1);

  // =========================================
  // SYMPTOMS
  // =========================================

  doc
    .fontSize(16)
    .font("Helvetica-Bold")
    .text("Reported Symptoms");

  doc.moveDown(0.5);

  doc.fontSize(11).font("Helvetica");

  if (record.symptoms && record.symptoms.length > 0) {
    record.symptoms.forEach((symptom) => {
      doc.text(`• ${symptom}`);
    });
  } else {
    doc.text("No symptoms provided.");
  }

  doc.moveDown(1);

  // =========================================
  // VITALS
  // =========================================

  doc
    .fontSize(16)
    .font("Helvetica-Bold")
    .text("Vitals");

  doc.moveDown(0.5);

  doc.fontSize(11).font("Helvetica");

  doc.text(`Blood Pressure: ${record.vitals?.bp || "Not provided"}`);

  doc.text(
    `Blood Sugar: ${
      record.vitals?.sugar !== null &&
      record.vitals?.sugar !== undefined
        ? record.vitals.sugar
        : "Not provided"
    }`
  );

  doc.moveDown(1);

  // =========================================
  // RISK ASSESSMENT
  // =========================================

  const aiResult = record.aiResult || {};

  doc
    .fontSize(16)
    .font("Helvetica-Bold")
    .text("Risk Assessment");

  doc.moveDown(0.5);

  doc
    .fontSize(13)
    .font("Helvetica-Bold")
    .text(`Risk Level: ${aiResult.riskLevel || "Not available"}`);

  doc.moveDown(0.7);

  // =========================================
  // RISK FACTORS
  // =========================================

  doc
    .fontSize(14)
    .font("Helvetica-Bold")
    .text("Risk Factors");

  doc.moveDown(0.4);

  doc.fontSize(11).font("Helvetica");

  if (aiResult.factors && aiResult.factors.length > 0) {
    aiResult.factors.forEach((factor) => {
      doc.text(`• ${factor}`);
    });
  } else {
    doc.text("No specific risk factors reported.");
  }

  doc.moveDown(1);

  // =========================================
  // ADVICE
  // =========================================

  doc
    .fontSize(14)
    .font("Helvetica-Bold")
    .text("Advice / Next Steps");

  doc.moveDown(0.4);

  doc.fontSize(11).font("Helvetica");

  doc.text(
    aiResult.advice || "No advice available.",
    {
      width: 495,
      lineGap: 4,
    }
  );

  doc.moveDown(1.5);

  // =========================================
  // DISCLAIMER
  // =========================================

  doc
    .fontSize(14)
    .font("Helvetica-Bold")
    .text("Important Disclaimer");

  doc.moveDown(0.4);

  doc
    .fontSize(10)
    .font("Helvetica")
    .text(
      aiResult.disclaimer ||
        "This screening is for preliminary informational purposes only and is not a substitute for professional medical advice, diagnosis, or treatment.",
      {
        width: 495,
        lineGap: 3,
      }
    );

  doc.moveDown(1);

  // =========================================
  // FOOTER
  // =========================================

  doc
    .fontSize(9)
    .font("Helvetica")
    .text(
      "Generated by SwasthyaScan",
      50,
      760,
      {
        align: "center",
        width: 495,
      }
    );

  // Finish PDF
  doc.end();
}

module.exports = {
  generateScreeningPDF,
};